# import time
# from selenium import webdriver
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("https://practice.automationtesting.in/")
# time.sleep(3)
# driver.execute_script("window.scrollBy(0, 600);")
# time.sleep(3)
# driver.find_element_by_class_name("product_tag-ruby").click()
# time.sleep(1)
# driver.find_element_by_class_name("reviews_tab").click()
# driver.find_element_by_class_name("star-5").click()
# review = driver.find_element_by_id("comment")
# review.send_keys("Nice book!")
# name = driver.find_element_by_id("author")
# name.send_keys("Gugarius")
# mail = driver.find_element_by_id("email")
# mail.send_keys("gug@gmail.com")
# driver.find_element_by_css_selector(".form-submit .submit").click()
# driver.quit()